---
title: "CaseStudyTwo"
author: "Jim Park Asha Saxena Andrew Walch"
date: "November 25, 2017"
output: 
   html_document:
      keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
#2a Read the csv into R and take a look at the data set. Output how many rows and columns the data.frame is.
PD <- read.csv("Procrastination.csv")
dim(PD) #results in printing the number of rows then the number of columns.
```




```{r}
#2b The column names are either too much or not enough. Change the column names so that they do not have spaces, underscores, slashes, and the like. All column names should be under 12 characters. Make sure you’re updating your codebook with information on the tidied data set as well.

class(PD)
OldNames <- names(PD)
library(data.table)
PD.renamed <- setnames(PD, old=OldNames, new=c("Age", "Gender", "Kids", "Education","WorkStatus","AnnualIncome", "Occupation", "Years", "Months", "Community", "Country", "Status", "NumSon", "NumDaught", "DP1", "DP2","DP3","DP4","DP5","AIP1","AIP2","AIP3","AIP4","AIP5","AIP6","AIP7","AIP8","AIP9","AIP10","AIP11","AIP12","AIP13","AIP14","AIP15", "GP1", "GP2", "GP3", "GP4", "GP5", "GP6", "GP7", "GP8", "GP9", "GP10", "GP11", "GP12", "GP13", "GP14", "GP15", "GP16", "GP17", "GP18", "GP19", "GP20", "SWLS1", "SWLS2", "SWLS3", "SWLS4", "SWLS5","Q1Self","Q2Others"))
head(PD.renamed)
```






## This is the part where the rationale for combining "teachers" needs to be explained.
```{r}
#2c. Some columns are, due to Qualtrics, malfunctioning. Prime examples are the following columns: “How long have you held this position?: Years”, Country of residence, Number of sons, and Current Occupation.

#i Some have impossible data values. Detail what you are doing to fix these columns in the raw data and why. It’s a judgment call for each, but explain why. For example, most people have not been doing anything for over 100 years. For the “Years” columns, round to the nearest integer.

#ii Somehow, “Number of sons” was labeled with Male (1) and Female (2). Change these incorrect labels back to integers.

#iii There are no “0” country of residences. Treat this as missing.

#iv Current Occupation has no “please specify” or “0.” Treat them as missing. Some jobs are quite similar. Use judgment calls to make overwrite them into the same category. It does not have to be 100% accurate, but right now “ESL Teacher” would not be counted as “teacher” if there were unique counts.

#2Ci. Fix impossible data values.  Round Age and Years to nearest integer (negative exponents will default to 0 due to this), Correct Years '999' entries and treat as missing(NA), and correct number of sons entries where Male = 1 sons, and Female =2 sons, Change 0 in "Country" to NA to indicate the data is missing, change "please specify" or "0" under Occupation to NA to indicate missing, and combine similar occupations into category of occupation.

PD.renamed$Age <- as.integer(round(PD.renamed$Age)) #rounds all Ages to the nearest integer and converts from numeric to integer.
PD.renamed$Years <- as.integer(round(PD.renamed$Years)) #rounds all Years to the nearest integer and converts from from numeric to integer.
PD.renamed$Years <- as.integer(gsub(999, NA, PD.renamed$Years)) #Removes 999 values and treats them as missing by indicating with an NA
PD.renamed$NumSon <- (gsub("Male", 1, PD.renamed$NumSon)) #subs a 1 where the word Male is listed in NumSon
PD.renamed$NumSon <- (gsub("Female", 2, PD.renamed$NumSon)) #subs a 2 where the word Female is listed in NumSon
PD.renamed$NumSon <- as.integer(PD.renamed$NumSon) #Converts NumSon to an integer.
PD.renamed$Country <- gsub(0, NA, PD.renamed$Country) #displays Country with 0 as missing data (NA)
PD.renamed$Country[PD.renamed$Country == ""] <- NA #replaces all non-entries with NA
PD.renamed$Occupation[PD.renamed$Occupation == 0] <- NA
PD.renamed$Occupation[PD.renamed$Occupation == "please specify"] <- NA
PD.renamed$Occupation[PD.renamed$Occupation == ""] <- NA
PD.renamed$Country[PD.renamed$Country == "Isreal"] <- "Israel" #Israel was mispelled.
PD.renamed$Q1Self[PD.renamed$Q1Self == ""] <- NA
PD.renamed$Q2Others <- as.character(PD.renamed$Q2Others)
PD.renamed$Q2Others[PD.renamed$Q2Others == ""] <- NA
PD.renamed$Q2Others[PD.renamed$Q2Others == "0"] <- NA
PD.renamed$Q2Others[PD.renamed$Q2Others == "4"] <- NA
PD.renamed$Q2Others <- as.factor(PD.renamed$Q2Others)
PD.renamed$Gender[PD.renamed$Gender == ""] <- NA
```



```{r}
#2e.  Each variable that starts with either DP, AIP, GP, or SWLS is an individual item on a scale. For example, DP 1 through DP 5 are five different questions on the Decision Procrastination Scale. I’ve reverse-scored them for you already, but you should create a new column for each of them with their mean. To clarify, you’ll need a DPMean column, an AIPMean column, a GPMean column, and a SWLSMean column. This represents the individual’s average decisional procrastination (DP), procrastination behavior (AIP), generalized procrastination (GP), and life satisfaction (SWLS).

PD.renamed$DPMean=rowMeans(PD.renamed[,15:19]) #Creates column for mean of all DP entries in observation.
PD.renamed$AIPMean=rowMeans(PD.renamed[,20:34]) #Creates column for mean of all AIP entries in observation.
PD.renamed$GPMean=rowMeans(PD.renamed[,35:54]) #Creates column for mean of all GP entries in observation.
PD.renamed$SWLSMean=rowMeans(PD.renamed[,55:59]) #Creates column for mean of all SWLS entries in observation.
PD.renamed[,62:65] <- round(PD.renamed[,62:65], digits = 3) #Round DP, AIP, GP, and SWLS means to 1 digit.
head(PD.renamed[,62:65])
```


```{r, echo = TRUE}
##3 SCRAPING
#3a Scraped Country and HDI

library('rvest') # grab and parse HTML

#Specifying the url for desired website to be scrapped
url <- 'https://en.wikipedia.org/wiki/List_of_countries_by_Human_Development_Index#Complete_list_of_countries'

webpage <- read_html(url)#Reading the HTML code from the website

#Using XPath selectors to scrap the Country and HDI of first 8 tables
Country<-webpage%>%html_nodes("h3+ div .wikitable:nth-child(1) td:nth-child(3)")%>%html_text()
HDI<-webpage%>%html_nodes("h3+ div td:nth-child(4)")%>%html_text()

###  WILL NEED TO FIX "WORLD" ENTRY
CountryHDI <- data.frame(Country, HDI)#Convert to data frame.
CountryHDI$HDI <- as.numeric(as.character(CountryHDI$HDI)) #Changes to numeric so we can later categorize
CountryHDI$Country <- as.character(CountryHDI$Country)
CountryHDI

## TODO need to fix "world" entry if teams decides it is necessary.
```



```{r}
#3b. Create a new column for this final scraped table which categories the Countries like the original page (Very high human development, High human development, Medium human development, Low human development). After these categories, output a csv file of this table to your repository.

CountryHDI$Category <- cut(CountryHDI$HDI, 
                       breaks = c(0, 0.55, 0.7, 0.8, 1.0), 
                       labels = c("Low", "Medium", "High", "VeryHigh"), 
                       right = FALSE)
CountryHDI
write.csv(CountryHDI, file = "CountryHDI.csv") #Creates csv file
```




```{r}
#3c Merge this data frame to the Country of Residence column of Procrastination.csv so that your data now has an HDI column and HDI categories (Very high human development, etc.).

CountryHDI$Country <- gsub(" ", "", CountryHDI$Country, fixed = TRUE) #Removes extra spaces that area not needed.
CountryHDI$Country <- gsub("(^\\s+)|(\\s+$)", "", CountryHDI$Country) #Removes extra spaces that area not needed.
PD.renamed$Country <- gsub("(^\\s+)|(\\s+$)", "", PD.renamed$Country) #Removes extra spaces that area not needed.
PD.renamed$Country <- gsub(" ", "", PD.renamed$Country, fixed = TRUE) #Removes extra spaces that area not needed.
CountryHDI$Country[CountryHDI$Country == "AntiguaandBarbuda"] <- "Antigua"
MergedData <- merge(CountryHDI, PD.renamed, by=c('Country'))
head(MergedData)
```




```{r}
#Code to identify country mismatches after merge including NA's.

library('plyr') # to call the count command

'%nin%' <- Negate('%in%')
pu <- unique(PD.renamed$Country)
hu <- unique(CountryHDI$Country)
a<- pu[pu %nin% hu]  #Finds unique Countries in the procrastination data set that are not in the HDI dataset. These are the ones that could not be matched up. 
a

```
#Comment:  The above coutry names were either not in the Procrastination set, Not listed (NA) or associated with another country (ie Taiwan/China)



```{r}
#4a Remove all observations where the participant is under age 18. No further analysis of underage individuals is permitted by your client. Remove any other age outliers as you see fit, but be sure to tell what you’re doing and why.

##REMOVED AGE = 80 (OUTLIER) BELOW.

MergedData.filt <- subset(MergedData, Age > 18)
MergedData.filt.b <- subset(MergedData.filt, Age != 80)
library('dplyr') # to call the count command
AgeFreq.noEighty <- count(MergedData.filt, Age)
AgeFreq.noEighty
AgeFreq<- count(MergedData.filt.b, Age) #Generates frequency table.  
AgeFreq #Verifies under 18 and 80 outlier is removed.
```



```{r}
#4b. Please provide (in pretty-fied table format or similar), descriptive statistics on Age, Income, HDI, and the four mean columns (DP, etc.). Create a simple histogram for two of these seven variables. Comment on the shape of the distribution in your markdown.

library(pastecs)
dfTemp <- MergedData.filt.b
attach(dfTemp)

dfTemp <- cbind(Age, AnnualIncome, as.double(HDI), DP1, AIP1, GP1, SWLS1)
colnames(dfTemp) <- c("Age", "AnnualIncome", "HDI", "DPMean", "AIPMean","GPMean", "SWLSMean")
options(scipen=100)
options(digits=0)
#stat.desc(dfTemp, basic=F)
stat.desc(dfTemp) #Provides statistical data.
dfTemp <- cbind(Age, AnnualIncome)
dfTemp <- data.frame(dfTemp)


hist(dfTemp$Age, ylim = c(0,800), main="Age Frequency Distribution", 
     xlab="Age", border="blue", ylab = "Age Frequency", col="lightgreen") 

# Age distribution is skewed right with the bulk of the age between 20 and 45.

hist(dfTemp$AnnualIncome, ylim = c(0,800), main="Income Frequency Distribution", 
     xlab="Income", border="blue", ylab = "Income Frequency", col="lightgreen") 

# Income distribution is skewed right with the bulk of the income between 0 and 100,000.
detach(dfTemp)
```



```{r}
#4c. Give the frequencies (in table format or similar) for Gender, Work Status, and Occupation. They can be separate tables, if that’s your choice.

library('dplyr') # to call the count command
GenderCount <- count(MergedData.filt.b, Gender)
WorkStatusCount <- count(MergedData.filt.b, WorkStatus)
OccupationCount <- count(MergedData.filt.b, Occupation)
GenderCount
WorkStatusCount
OccupationCount
```



```{r}
#4d. Give the counts (again, pretty table) of how many participants per country in descending order.
library(dplyr)
dfTempCounts <- MergedData.filt.b
attach(dfTempCounts)

 dfTempCounts %>% select(Country) %>% group_by(Country) %>% 
  dplyr::summarise(Participant_Count = n()) %>% 
  plyr::arrange(desc(Participant_Count))
```

```{r}
#4e. There are two variables in the set: whether the person considers themselves a procrastinator (yes/no) and whether others consider them a procrastinator (yes/no). How many people matched their perceptions to others’ (so, yes/yes and no/no)? To clarify: how many people said they felt they were procrastinators and also said others thought they were procrastinators? Likewise, how many said they were not procrastinators and others also did not think they were procrastinators?

  x <- MergedData.filt.b %>% select(Q1Self, Q2Others)
  x$Q1Self <- as.character(x$Q1Self)#self Responce
  x$Q2Others <- as.character(x$Q2Others)#other views
  
  x %>% select(Q1Self,Q2Others) %>% ungroup() %>%#ungroup responces
  filter(base::nchar(Q1Self)>0 & base::nchar(Q2Others)>0) %>% #filters Q1self and Q2Others responces
  filter(Q1Self==Q2Others) %>% group_by(Q1Self) %>% #compares Q1 abd Q2 to eachother
  dplyr::summarise(InAgreement_Count = n()) %>% 
  rename(InAgreement = Q1Self)
```






```{r}
#5b. Create a barchart in ggplot or similar which displays the top 15 nations in average procrastination scores, using one measure of the following: DP, AIP, or GP. The bars should be in descending order, with the number 1 most procrastinating nation at the top and 15th most procrastinating at the bottom. Omit all other nations. Color the bars by HDI category (see 3B). Use any color palette of your choice other than the default.
library(ggplot2)
library(RColorBrewer)
library(dplyr)
ByCountry<- group_by(MergedData.filt.b, MergedData.filt.b$Country) #Organizes by country
CountryAIPMean <- summarize(ByCountry,CAIPMean = mean(AIPMean)) # Summarizes by country and finds mean of AIP means of all observations, then assigns to dataframe
CountryAIPMean <- rename(CountryAIPMean, 'Country' = 'MergedData.filt.b$Country') #rename so we can merge by country
CountryAIPMean.Cat <- merge(CountryAIPMean, CountryHDI, by=c('Country')) #Attaches Categry to countries
desOrder<- CountryAIPMean.Cat[order(-CountryAIPMean.Cat$CAIPMean),] #Orders by AIPMean descending
Des <- head(desOrder, n=15) #Assigns 15 entries only

ggplot(data=Des, aes(x=reorder(Country, -CAIPMean), y=CAIPMean, fill=Category)) +
geom_bar(stat = "identity")+
theme(axis.text.x=element_text(angle=90,vjust=0.5)) + xlab("Country") +
ylab("AIPMean") + ggtitle("Adult Inventory of Procrastication(AIP) Mean by Top 15 Countries")+
scale_fill_brewer(palette= "Spectral") +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
#5c. Create another barchart identical in features to 5B, but use another one of the three variables: DP, AIP, or GP. How many nations show up both in 5B’s plot and 5C’s? Which, if any?
CountryDPMean <- summarize(ByCountry,CDPMean = mean(DPMean)) # Summarizes by country and finds mean of DP means of all observations, then assigns to dataframe
CountryDPMean <- rename(CountryDPMean, 'Country' = 'MergedData.filt.b$Country') #rename so we can merge by country
CountryDPMean.Cat <- merge(CountryDPMean, CountryHDI, by=c('Country')) #Attaches Categry to countries
desOrder.DP<- CountryDPMean.Cat[order(-CountryDPMean.Cat$CDPMean),] #Orders by AIPMean descending
Des.DP <- head(desOrder.DP, n=15) #Assigns 15 entries only
ggplot(data=Des.DP, aes(x=reorder(Country, -CDPMean), y=CDPMean, fill=Category)) +
geom_bar(stat = "identity")+
theme(axis.text.x=element_text(angle=90,vjust=0.5)) + xlab("Country") +
ylab("DPMean") + ggtitle("Decisional Procrastination Scale (DP) Mean by Top 15 Countries")+
  scale_fill_brewer(palette= "Spectral") +
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
#5d. Is there a relationship between Age and Income? Create a scatterplot and make an assessment of whether there is a relationship. Color each point based on the Gender of the participant. You’re welcome to use lm() or similar functions to back up your claims.

ggplot(data=subset(MergedData.filt.b, !is.na(Gender)), aes(x = Age, y = AnnualIncome, color=Gender)) + 
  geom_point(size = 1, na.rm=TRUE) + 
  labs(title = "Relationship between Income and Age by Gender") + 
  geom_smooth(method=lm, se=FALSE, size = 1, na.rm=TRUE)+   #adds linear fit model to more clearly see patterns.
  theme(plot.title = element_text(hjust = 0.5))
```





##TODO RELABEL ALL CHARTS WITH MEANINGFULL TITLES.
```{r}
#5e What about Life Satisfaction and HDI? Create another scatterplot. Is there a discernible relationship there? What about if you used the HDI category instead and made a barplot?

ggplot(MergedData.filt.b, aes(x = HDI, y = SWLSMean)) + 
  geom_point(colour = 'red', size = 1, na.rm=TRUE) + 
  labs(title = "Relationship between Human Development Index(HDI) and Life Satisfaction (SWLS)") + 
  geom_smooth(method=lm, se=FALSE, size = 1, na.rm=TRUE)+   #adds linear fit model to more clearly see patterns.
  theme(plot.title = element_text(hjust = 0.5))
```
#5e Barplot
```{r}
#5e Barplot

ggplot(MergedData.filt.b, aes(x = Category, y = SWLSMean)) + 
  geom_bar(stat = "identity", fill='red', na.rm=TRUE) +
  labs(title = "Relationship between Human Development Index(HDI) & Life Satisfaction (SWLS)") + 
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
#6 Outputting to CSV format – Make sure there are no index numbers (10%)
#6a The client would like the finalized HDI table (3A and 3B)

library(gridExtra)
pdf(file = "HDI.pdf", height = 54, width = 7)
grid.table(CountryHDI, cols = colnames(CountryHDI), rows = NULL)
dev.off()
```


```{r}
#6b. The client would like the Tidied version of the original input to be output in the repository, including the merged HDI data (3C).

write.csv(MergedData.filt.b, file = "MergedDataProcrastinationHDI.csv",row.names=FALSE)
```



```{r}
#6c The client would like a dataset (or two) that shows the Top 15 nations (in 5B and 5C), as well as their HDI scores.

library(dplyr)
Des.DP.ColsRemoved <- select(Des.DP, Country, CDPMean, HDI)
write.csv(Des.DP.ColsRemoved, file = "Top15CountriesHDI.csv",row.names=FALSE)
```
